
import React, { useState, useEffect } from 'react';
import { Advice, AdviceMood } from '../types';
import { MOOD_COLORS } from '../constants';
import { getAdviceBackstory } from '../services/geminiService';

interface AdviceCardProps {
  advice: Advice | null;
  loading: boolean;
  onClick: () => void;
  isFavorite?: boolean;
  onToggleFavorite?: () => void;
}

interface IconWrapperProps {
  children: React.ReactNode;
  className?: string;
}

const IconWrapper: React.FC<IconWrapperProps> = ({ children, className = "" }) => (
  <div className={`transition-transform duration-300 group-hover:scale-110 group-active:scale-90 group-active:rotate-3 ${className}`}>
    {children}
  </div>
);

const AdviceCard: React.FC<AdviceCardProps> = ({ advice, loading, onClick, isFavorite, onToggleFavorite }) => {
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const [backstory, setBackstory] = useState<string | null>(null);
  const [isExplaining, setIsExplaining] = useState(false);
  const [showBackstory, setShowBackstory] = useState(false);
  const [justFavorited, setJustFavorited] = useState(false);
  const [backstoryError, setBackstoryError] = useState(false);

  const currentMood = advice?.mood || AdviceMood.LIGHTHEARTED;
  const colors = MOOD_COLORS[currentMood];

  useEffect(() => {
    setBackstory(null);
    setShowBackstory(false);
    setIsExplaining(false);
    setBackstoryError(false);
  }, [advice]);

  const handleToggleFavorite = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!isFavorite) {
      setJustFavorited(true);
      setTimeout(() => setJustFavorited(false), 800);
    }
    onToggleFavorite?.();
  };

  const handleCopy = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!advice) return;
    try {
      await navigator.clipboard.writeText(advice.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Copy failed", err);
    }
  };

  const handleShare = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!advice) return;

    const shareTitle = 'Zen_X_Zany Insight Payload';
    const shareText = `"${advice.text}"\n\nGenerated by Zen_X_Zany Advice Engine.`;
    const shareUrl = window.location.origin;
    const shareFullContent = `${shareText}\n${shareUrl}`;
    
    const triggerFeedback = () => {
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    };

    if (navigator.share) {
      try {
        await navigator.share({
          title: shareTitle,
          text: shareText,
          url: shareUrl
        });
        triggerFeedback();
      } catch (err) {
        if (err instanceof Error && err.name !== 'AbortError') {
          fallbackToClipboard(shareFullContent, triggerFeedback);
        }
      }
    } else {
      fallbackToClipboard(shareFullContent, triggerFeedback);
    }
  };

  const fallbackToClipboard = async (content: string, callback: () => void) => {
    try {
      await navigator.clipboard.writeText(content);
      callback();
    } catch (err) {
      console.error("Sharing fallback failed", err);
    }
  };

  const handleExplain = async (e?: React.MouseEvent) => {
    e?.stopPropagation();
    if (!advice || isExplaining) return;
    
    if (backstory && !backstoryError) {
      setShowBackstory(!showBackstory);
      return;
    }

    setIsExplaining(true);
    setBackstoryError(false);
    try {
      const explanation = await getAdviceBackstory(advice.text, advice.mood);
      setBackstory(explanation);
      setBackstoryError(false);
      setShowBackstory(true);
    } catch (err) {
      setBackstory("UNABLE_TO_RETRIEVE_CONTEXT");
      setBackstoryError(true);
      setShowBackstory(true);
    } finally {
      setIsExplaining(false);
    }
  };

  return (
    <div 
      onClick={onClick}
      className={`
        relative w-full max-w-5xl transition-all duration-300 cursor-pointer group/card
        ${loading ? 'opacity-50 pointer-events-none' : 'opacity-100'}
      `}
    >
      {/* The Slab */}
      <div className={`
        bg-white border-[4px] md:border-[6px] border-black p-5 sm:p-8 md:p-12 pb-14 sm:pb-16 md:pb-20 slab-shadow relative overflow-hidden flex flex-col md:flex-row gap-8 md:gap-12
        transition-transform duration-300 ${loading ? 'translate-x-2 translate-y-2' : 'group-hover/card:-translate-x-1 group-hover/card:-translate-y-1'}
      `}>
        
        {/* Mood Indicator Stripe */}
        <div className={`absolute top-0 left-0 w-full h-[8px] md:h-[12px] ${colors.primary}`} />

        {/* 1. Primary Text Side */}
        <div className="flex-[2] relative min-h-[250px] sm:min-h-[300px] md:min-h-[350px] flex flex-col justify-center">
          <div className="font-mono text-[10px] md:text-[12px] font-bold mb-6 md:mb-8 uppercase tracking-widest flex items-center gap-2">
             <div className="w-2 md:w-3 h-2 md:h-3 bg-black animate-ping" />
             Insight_Payload
          </div>

          <div className="relative">
            <h2 className={`
              text-3xl sm:text-4xl md:text-5xl lg:text-7xl font-bold leading-[1.1] md:leading-[1] tracking-tighter uppercase break-words
              transition-all duration-700 ease-[cubic-bezier(0.16,1,0.3,1)]
              ${showBackstory ? 'opacity-0 scale-95 -translate-y-8 blur-sm' : 'opacity-100 scale-100 translate-y-0 blur-0'}
            `}>
              {advice?.text}
            </h2>

            {/* Backstory Pane (Thought Bubble Style) */}
            <div className={`
              absolute inset-0 flex flex-col justify-center transition-all duration-700 delay-100 ease-[cubic-bezier(0.16,1,0.3,1)]
              ${showBackstory ? 'opacity-100 translate-y-0 scale-100' : 'opacity-0 translate-y-12 scale-95 pointer-events-none'}
            `}>
              <div className="relative bg-white border-[3px] md:border-[4px] border-black p-5 sm:p-6 md:p-10 slab-shadow-sm transition-transform duration-500 ease-out">
                <div className="absolute -bottom-4 md:-bottom-6 left-12 w-6 md:w-8 h-6 md:h-8 bg-white border-r-[3px] md:border-r-[4px] border-b-[3px] md:border-b-[4px] border-black transform rotate-45 -z-10" />
                
                <span className="font-mono text-[10px] font-bold uppercase mb-3 md:mb-4 text-[#FF4D00] block tracking-widest">
                  Contextual_Analysis // {backstoryError ? 'ERROR_DETECTED' : 'Why this advice?'}
                </span>
                
                <p className={`text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold leading-tight font-mono lowercase animate-content-appear ${backstoryError ? 'text-red-600' : 'text-black'}`}>
                  {backstory}
                </p>

                <div className="mt-6 md:mt-8 flex flex-wrap gap-3 md:gap-4">
                  {backstoryError && (
                    <button 
                      onClick={(e) => { e.stopPropagation(); handleExplain(e); }}
                      disabled={isExplaining}
                      className="font-mono text-[10px] font-bold uppercase bg-[#FF4D00] text-black px-3 md:px-4 py-2 hover:bg-black hover:text-white transition-colors active:translate-y-1 disabled:opacity-50"
                    >
                      {isExplaining ? 'RETRYING...' : 'RETRY_ANALYSIS'}
                    </button>
                  )}
                  <button 
                    onClick={(e) => { e.stopPropagation(); setShowBackstory(false); }}
                    className="font-mono text-[10px] font-bold uppercase bg-black text-white px-3 md:px-4 py-2 hover:bg-[#FF4D00] transition-colors active:translate-y-1"
                  >
                    {backstoryError ? 'DISMISS' : 'RETURN_TO_CORE'}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* 2. Metadata / Controls Side */}
        <div className="flex-1 flex flex-col justify-between border-t-[3px] md:border-t-0 md:border-l-[3px] border-black pt-6 md:pt-0 md:pl-10 lg:pl-12">
          
          <div className="flex flex-row md:flex-col justify-between md:justify-start gap-4 md:gap-6">
            <div className="flex flex-col">
              <span className="font-mono text-[9px] md:text-[10px] uppercase font-bold text-gray-400">Classification</span>
              <span className={`text-lg md:text-xl font-bold uppercase ${colors.accent}`}>{currentMood}</span>
            </div>
            
            <div className="flex flex-col items-end md:items-start">
              <span className="font-mono text-[9px] md:text-[10px] uppercase font-bold text-gray-400">ID_Hex</span>
              <span className="font-mono text-[10px] md:text-xs">#{Math.random().toString(16).slice(2, 8).toUpperCase()}</span>
            </div>
          </div>

          {/* Action Grid */}
          <div className="grid grid-cols-1 gap-3 mt-6 md:mt-8">
             <button 
               onClick={handleExplain}
               className="group bg-black text-white p-3 md:p-4 font-mono text-[10px] font-bold uppercase flex items-center justify-between hover:bg-[#FF4D00] transition-colors"
               title="Analyze backstory"
             >
               <span>{isExplaining ? 'ANALYZING...' : showBackstory ? 'CLOSE' : 'EXPLAIN'}</span>
               <IconWrapper>
                 <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="square"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></svg>
               </IconWrapper>
             </button>

             <div className="flex gap-2 sm:gap-3">
               {/* Favorite Column */}
               <div className="relative flex-1">
                 <div className={`absolute -top-10 left-1/2 -translate-x-1/2 font-mono text-[9px] md:text-[10px] font-bold text-[#FF4D00] transition-all duration-700 pointer-events-none ${justFavorited ? 'opacity-100 -translate-y-4 scale-125' : 'opacity-0 translate-y-0 scale-100'}`}>
                   SAVED!
                 </div>
                 {justFavorited && <div className="absolute inset-0 border-4 border-[#FF4D00] rounded-none animate-radiate-ring-orange pointer-events-none z-10" />}
                 <button 
                   onClick={handleToggleFavorite}
                   className={`group w-full border-[3px] md:border-[4px] border-black p-3 md:p-4 font-mono text-[9px] md:text-[10px] font-bold uppercase flex items-center justify-center transition-all ${isFavorite ? 'bg-[#FF4D00] text-black border-orange-600 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] md:shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]' : 'bg-white text-black hover:bg-gray-100'}`}
                   title={isFavorite ? "Remove from favorites" : "Add to favorites"}
                 >
                   <IconWrapper className={justFavorited ? 'animate-heartbeat-sparkle' : ''}>
                     <svg width="18" height="18" viewBox="0 0 24 24" fill={isFavorite ? "currentColor" : "none"} stroke="currentColor" strokeWidth="3" strokeLinecap="square">
                      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
                     </svg>
                   </IconWrapper>
                 </button>
               </div>

               {/* Copy Column */}
               <button 
                 onClick={handleCopy}
                 className="group flex-1 bg-white border-[3px] md:border-[4px] border-black p-3 md:p-4 font-mono text-[9px] md:text-[10px] font-bold uppercase flex items-center justify-center hover:bg-black hover:text-white transition-all"
                 title="Copy to clipboard"
               >
                 <IconWrapper>
                   {copied ? (
                     <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#22c55e" strokeWidth="4" strokeLinecap="square"><polyline points="20 6 9 17 4 12"/></svg>
                   ) : (
                     <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="square"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
                   )}
                 </IconWrapper>
               </button>

               {/* Share Column */}
               <div className="relative flex-1">
                 <div className={`absolute -top-10 left-1/2 -translate-x-1/2 font-mono text-[9px] md:text-[10px] font-bold text-blue-600 transition-all duration-700 pointer-events-none ${shared ? 'opacity-100 -translate-y-4 scale-125' : 'opacity-0 translate-y-0 scale-100'}`}>
                   TRANSMITTED!
                 </div>
                 {shared && <div className="absolute inset-0 border-4 border-blue-600 rounded-none animate-radiate-ring-blue pointer-events-none z-10" />}
                 
                 <button 
                   onClick={handleShare}
                   className={`group w-full border-[3px] md:border-[4px] border-black p-3 md:p-4 font-mono text-[9px] md:text-[10px] font-bold uppercase flex items-center justify-center transition-all ${shared ? 'bg-blue-50' : 'bg-white hover:bg-black hover:text-white'}`}
                   title="Transmit output"
                 >
                   <IconWrapper>
                     {shared ? (
                       <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="square"><polyline points="20 6 9 17 4 12"/></svg>
                     ) : (
                       <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="square"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8M16 6l-4-4-4 4M12 2v13"/></svg>
                     )}
                   </IconWrapper>
                 </button>
               </div>
             </div>
          </div>
        </div>

        {/* Action Prompt - Centered at the bottom */}
        <div className="absolute bottom-3 left-0 w-full flex justify-center px-4 pointer-events-none">
          <span className="font-mono text-[8px] md:text-[9px] font-bold uppercase tracking-[0.2em] text-gray-400/60 flex items-center gap-2">
            <span className="w-1 h-1 bg-gray-300 rounded-full animate-pulse" />
            Tap card for new wisdom
            <span className="w-1 h-1 bg-gray-300 rounded-full animate-pulse" />
          </span>
        </div>
      </div>
      
      {/* Decorative Blueprint Markers */}
      <div className="absolute -top-4 -left-4 font-mono text-[9px] md:text-[10px] text-gray-300 select-none">UL_COORD_001</div>
      <div className="absolute -bottom-4 -right-4 font-mono text-[9px] md:text-[10px] text-gray-300 select-none">LR_COORD_999</div>

      <style>{`
        .slab-shadow-sm {
          box-shadow: 4px 4px 0px 0px #000;
        }
        @media (min-width: 768px) {
          .slab-shadow-sm {
            box-shadow: 6px 6px 0px 0px #000;
          }
        }
        @keyframes icon-bounce {
          0%, 100% { transform: scale(1); }
          50% { transform: scale(0.85); }
        }
        @keyframes heartbeat-sparkle {
          0% { transform: scale(1); filter: drop-shadow(0 0 0px #FF4D00); }
          20% { transform: scale(1.6); filter: drop-shadow(0 0 12px #FF4D00); }
          40% { transform: scale(1.1); filter: drop-shadow(0 0 4px #FF4D00); }
          60% { transform: scale(1.4); filter: drop-shadow(0 0 10px #FF4D00); }
          80% { transform: scale(1.2); filter: drop-shadow(0 0 2px #FF4D00); }
          100% { transform: scale(1); filter: drop-shadow(0 0 0px #FF4D00); }
        }
        @keyframes radiate-ring-orange {
          0% { transform: scale(1); opacity: 1; border-color: #FF4D00; border-width: 4px; }
          100% { transform: scale(2.5); opacity: 0; border-color: #FF4D00; border-width: 0px; }
        }
        @keyframes radiate-ring-blue {
          0% { transform: scale(1); opacity: 1; border-color: #2563eb; border-width: 4px; }
          100% { transform: scale(2.5); opacity: 0; border-color: #2563eb; border-width: 0px; }
        }
        @keyframes content-appear {
          from { opacity: 0; transform: scale(0.98); }
          to { opacity: 1; transform: scale(1); }
        }
        .animate-radiate-ring-orange {
          animation: radiate-ring-orange 0.6s cubic-bezier(0.19, 1, 0.22, 1) forwards;
        }
        .animate-radiate-ring-blue {
          animation: radiate-ring-blue 0.6s cubic-bezier(0.19, 1, 0.22, 1) forwards;
        }
        .animate-heartbeat-sparkle {
          animation: heartbeat-sparkle 0.8s cubic-bezier(0.175, 0.885, 0.32, 1.275);
        }
        .animate-content-appear {
          animation: content-appear 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards;
        }
        .group:active svg {
          animation: icon-bounce 0.2s ease-in-out;
        }
      `}</style>
    </div>
  );
};

export default AdviceCard;
