import React, { useState, useEffect } from 'react';
import { Advice, AdviceMood } from '../types';
import { MOOD_COLORS } from '../constants';
import { getAdviceBackstory } from '../services/geminiService';

interface AdviceCardProps {
  advice: Advice | null;
  loading: boolean;
  onClick: () => void;
  isFavorite?: boolean;
  isDarkMode?: boolean;
  onToggleFavorite?: () => void;
}

const IconWrapper: React.FC<{ children: React.ReactNode; className?: string }> = ({ children, className = "" }) => (
  <div className={`transition-transform duration-300 group-hover:scale-110 group-active:scale-90 ${className}`}>
    {children}
  </div>
);

const AdviceCard: React.FC<AdviceCardProps> = ({ advice, loading, onClick, isFavorite, isDarkMode, onToggleFavorite }) => {
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const [backstory, setBackstory] = useState<string | null>(null);
  const [isExplaining, setIsExplaining] = useState(false);
  const [showBackstory, setShowBackstory] = useState(false);
  const [justFavorited, setJustFavorited] = useState(false);
  const [backstoryError, setBackstoryError] = useState(false);

  const currentMood = advice?.mood || AdviceMood.LIGHTHEARTED;
  const colors = MOOD_COLORS[currentMood];

  useEffect(() => {
    setBackstory(null);
    setShowBackstory(false);
    setIsExplaining(false);
    setBackstoryError(false);
  }, [advice]);

  const handleToggleFavorite = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!isFavorite) {
      setJustFavorited(true);
      setTimeout(() => setJustFavorited(false), 800);
    }
    onToggleFavorite?.();
  };

  const handleCopy = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!advice) return;
    try {
      await navigator.clipboard.writeText(advice.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) { console.error("Copy failed", err); }
  };

  const handleShare = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!advice) return;
    const shareText = `"${advice.text}"\n\nGenerated by Zen_X_Zany Advice Engine.`;
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Zen_X_Zany Payload', text: shareText, url: window.location.origin });
        setShared(true); setTimeout(() => setShared(false), 2000);
      } catch (err) { if (err instanceof Error && err.name !== 'AbortError') fallbackCopy(shareText); }
    } else { fallbackCopy(shareText); }
  };

  const fallbackCopy = async (text: string) => {
    try { await navigator.clipboard.writeText(text); setShared(true); setTimeout(() => setShared(false), 2000); } catch (e) {}
  };

  const handleExplain = async (e?: React.MouseEvent) => {
    e?.stopPropagation();
    if (!advice || isExplaining) return;
    if (backstory && !backstoryError) {
      setShowBackstory(!showBackstory);
      return;
    }
    setIsExplaining(true);
    setBackstoryError(false);
    try {
      const explanation = await getAdviceBackstory(advice.text, advice.mood);
      setBackstory(explanation);
      setShowBackstory(true);
    } catch (err) {
      setBackstory("UNABLE_TO_RETRIEVE_CONTEXT");
      setBackstoryError(true);
      setShowBackstory(true);
    } finally { setIsExplaining(false); }
  };

  const cardBg = isDarkMode ? 'bg-[#1a1a1a]' : 'bg-white';
  const cardBorder = isDarkMode ? 'border-white' : 'border-black';
  const cardText = isDarkMode ? 'text-white' : 'text-black';
  const backstoryBg = isDarkMode ? 'bg-zinc-800' : 'bg-white';
  const shadowClass = isDarkMode ? 'slab-shadow-white' : 'slab-shadow';

  return (
    <div onClick={onClick} className={`relative w-full max-w-5xl transition-all duration-300 cursor-pointer group/card ${loading ? 'opacity-50 pointer-events-none' : 'opacity-100'}`}>
      <div className={`${cardBg} ${cardBorder} border-[4px] md:border-[6px] p-5 sm:p-8 md:p-12 pb-14 sm:pb-16 md:pb-20 ${shadowClass} relative overflow-hidden flex flex-col md:flex-row gap-8 md:gap-12 transition-transform duration-300 ${loading ? 'translate-x-2 translate-y-2' : 'group-hover/card:-translate-x-1 group-hover/card:-translate-y-1'}`}>
        <div className={`absolute top-0 left-0 w-full h-[8px] md:h-[12px] ${colors.primary}`} />
        <div className="flex-[2] relative min-h-[250px] sm:min-h-[300px] flex flex-col justify-center">
          <div className="font-mono text-[10px] md:text-[12px] font-bold mb-6 md:mb-8 uppercase tracking-widest flex items-center gap-2">
             <div className={`w-2 h-2 ${isDarkMode ? 'bg-white' : 'bg-black'} animate-ping`} />
             Insight_Payload
          </div>
          <div className="relative">
            <h2 className={`text-3xl sm:text-4xl md:text-5xl lg:text-7xl font-bold leading-[1.1] tracking-tighter uppercase transition-all duration-700 ${showBackstory ? 'opacity-0 scale-95 blur-sm' : 'opacity-100 scale-100'} ${cardText}`}>
              {advice?.text}
            </h2>
            <div className={`absolute inset-0 flex flex-col justify-center transition-all duration-700 ${showBackstory ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-12 pointer-events-none'}`}>
              <div className={`relative ${backstoryBg} border-[3px] md:border-[4px] ${cardBorder} p-5 sm:p-10 ${isDarkMode ? 'slab-shadow-white' : 'slab-shadow-sm'}`}>
                <div className={`absolute -bottom-4 left-12 w-6 h-6 ${backstoryBg} border-r-[3px] border-b-[3px] ${cardBorder} transform rotate-45 -z-10`} />
                <span className="font-mono text-[10px] font-bold uppercase mb-4 text-[#FF4D00] block tracking-widest">Contextual_Analysis</span>
                <p className={`text-lg md:text-2xl font-bold font-mono lowercase ${backstoryError ? 'text-red-500' : cardText}`}>{backstory}</p>
                <div className="mt-8 flex gap-4">
                  <button onClick={(e) => { e.stopPropagation(); setShowBackstory(false); }} className={`font-mono text-[10px] font-bold uppercase px-4 py-2 transition-colors ${isDarkMode ? 'bg-white text-black hover:bg-[#FF4D00] hover:text-white' : 'bg-black text-white hover:bg-[#FF4D00]'}`}>RETURN</button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className={`flex-1 flex flex-col justify-between border-t-[3px] md:border-t-0 md:border-l-[3px] ${cardBorder} pt-6 md:pt-0 md:pl-10`}>
          <div className="flex flex-row md:flex-col justify-between gap-4">
            <div className="flex flex-col">
              <span className="font-mono text-[9px] uppercase font-bold text-gray-500">Classification</span>
              <span className={`text-lg md:text-xl font-bold uppercase ${colors.accent}`}>{currentMood}</span>
            </div>
            <div className="flex flex-col items-end md:items-start">
              <span className="font-mono text-[9px] uppercase font-bold text-gray-500">ID_Hex</span>
              <span className={`font-mono text-[10px] ${cardText}`}>#{advice?.id || 'PENDING'}</span>
            </div>
          </div>
          <div className="grid grid-cols-1 gap-3 mt-8">
             <button onClick={handleExplain} className={`group p-3 md:p-4 font-mono text-[10px] font-bold uppercase flex items-center justify-between transition-colors ${isDarkMode ? 'bg-white text-black hover:bg-[#FF4D00] hover:text-white' : 'bg-black text-white hover:bg-[#FF4D00]'}`}>
               <span>{isExplaining ? 'ANALYZING...' : showBackstory ? 'CLOSE' : 'EXPLAIN'}</span>
               <IconWrapper><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></svg></IconWrapper>
             </button>
             <div className="flex gap-2">
               <button onClick={handleToggleFavorite} className={`flex-1 border-[3px] md:border-[4px] ${cardBorder} p-3 md:p-4 font-mono text-[10px] font-bold uppercase flex items-center justify-center transition-all ${isFavorite ? 'bg-[#FF4D00] text-black border-orange-600' : isDarkMode ? 'bg-zinc-800 text-white hover:bg-[#FF4D00] hover:text-white' : 'bg-white text-black hover:bg-gray-100'}`}>
                 <IconWrapper><svg width="18" height="18" viewBox="0 0 24 24" fill={isFavorite ? "currentColor" : "none"} stroke="currentColor" strokeWidth="3"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg></IconWrapper>
               </button>
               <button onClick={handleCopy} className={`flex-1 border-[3px] md:border-[4px] ${cardBorder} p-3 md:p-4 font-mono text-[10px] font-bold uppercase flex items-center justify-center transition-all ${isDarkMode ? 'bg-zinc-800 text-white hover:bg-white hover:text-black' : 'bg-white text-black hover:bg-black hover:text-white'}`}>
                 <IconWrapper>{copied ? <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#22c55e" strokeWidth="4"><polyline points="20 6 9 17 4 12"/></svg> : <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>}</IconWrapper>
               </button>
               <button onClick={handleShare} className={`flex-1 border-[3px] md:border-[4px] ${cardBorder} p-3 md:p-4 font-mono text-[10px] font-bold uppercase flex items-center justify-center transition-all ${isDarkMode ? 'bg-zinc-800 text-white hover:bg-blue-600' : 'bg-white text-black hover:bg-black hover:text-white'}`}>
                 <IconWrapper><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8M16 6l-4-4-4 4M12 2v13"/></svg></IconWrapper>
               </button>
             </div>
          </div>
        </div>
        <div className="absolute bottom-3 left-0 w-full flex justify-center pointer-events-none">
          <span className="font-mono text-[8px] font-bold uppercase tracking-[0.2em] text-gray-500/60">Tap card for new wisdom</span>
        </div>
      </div>
      <style>{`
        .slab-shadow-sm { box-shadow: 4px 4px 0px 0px #000; }
        .slab-shadow-white { box-shadow: 8px 8px 0px 0px #fff; }
        @media (min-width: 768px) { .slab-shadow-sm { box-shadow: 6px 6px 0px 0px #000; } }
      `}</style>
    </div>
  );
};

export default AdviceCard;